### ISSUE TITLE
컨트리뷰션 가이드

### ISSUE THREAD

**Issue by JeffGuKang** [clien-devgroup/developer-tools#1]
컨트리뷰션 가이드가 필요합니다. 
입문자들을 위한 수정 및 PR까지의 과정이 대략적으로 있으면 어떨까요?

**Comment by devyohan** [comment]
이 이슈를 이제 봤네요. 좋습니다. 

우선 저는 https://naver.github.io/OpenSourceGuide/book/BetterContribution/why-contribute-to-open-source.html
글을 추천해봅니다.

가능하면 잘 작성된 저희에게 맞는 컨트리뷰선 가이드라인을 마크다운으로 작성해보면 어떨까 합니다.

**Comment by JeffGuKang** [comment]
참고하기 좋은 링크 같습니다. 

마크다운 내용은 
https://github.com/milooy/remote-or-flexible-work-company-in-korea/blob/master/contributing.md
등을 참고하여 일단 간단하게 적고 필요할때 업데이트 해나가도 좋을 것 같네요. 

이것은 GitHub 공식 [contribution 가이드라인 링크](https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors)입니다. 

참고하셔서 

- contributing.md 생성
- contribution guide 작성 

로 진행해주시면 될 것 같습니다. 지원자를 기다립니다.

**Comment by JeffGuKang** [comment]
요한님께 할당해 드렸습니다. branch 네임을 `1-contribution-guide` 이런식으로 만드셔도 좋습니다.
